apiVersion: v1
kind: Service
metadata: 
  name: svc-myclinic-com
  labels: 
    app: myclinic-endpoints
spec:
  type: NodePort
  selector:
    app: api.myclinic.com
  ports:
    - port: 3000
      targetPort: 3000
      nodePort: 30018