apiVersion: v1
kind: Service
metadata:
  name: db-svc
  labels:
    app: svc.db.myclinic.com
spec:
  type: NodePort
  selector:
    app: db.myclinic
  ports:
    - port: 27017
      targetPort: 27017
      nodePort: 30017